import { CREATE_PRODUCT_TYPE, DELETE_PRODUCT_TYPE, UPDATE_PRODUCT_TYPE } from "@/api/mutations";
import { FIND_MANY_PRODUCT_TYPES, FIND_ONE_PRODUCT_TYPE } from "@/api/queries";

export const CREATE_ITEM = CREATE_PRODUCT_TYPE;
export const DELETE_ITEM = DELETE_PRODUCT_TYPE;
export const FIND_MANY_ITEMS = FIND_MANY_PRODUCT_TYPES;
export const FIND_ONE_ITEM = FIND_ONE_PRODUCT_TYPE;
export const UPDATE_ITEM = UPDATE_PRODUCT_TYPE;
