import {
  CREATE_PRODUCT_TEMPLATE,
  DELETE_PRODUCT_TEMPLATE,
  UPDATE_PRODUCT_TEMPLATE,
  UPDATE_PRODUCT_TEMPLATE_IMAGES,
} from "@/api/mutations";
import {
  FIND_MANY_PRODUCT_TEMPLATES,
  FIND_ONE_PRODUCT_TEMPLATE,
} from "@/api/queries";

export const CREATE_ITEM = CREATE_PRODUCT_TEMPLATE;
export const DELETE_ITEM = DELETE_PRODUCT_TEMPLATE;
export const FIND_MANY_ITEMS = FIND_MANY_PRODUCT_TEMPLATES;
export const FIND_ONE_ITEM = FIND_ONE_PRODUCT_TEMPLATE;
export const UPDATE_ITEM = UPDATE_PRODUCT_TEMPLATE;
export const UPDATE_ITEM_IMAGES = UPDATE_PRODUCT_TEMPLATE_IMAGES;
