ALTER TYPE "PricingName" ADD VALUE IF NOT EXISTS 'DRIVER_REQUEST_FEE';

ALTER TABLE "Partner"
ADD COLUMN "driverRequestFee" DOUBLE PRECISION;

ALTER TABLE "PartnerDriverRequest"
ADD COLUMN "assignedAt" TIMESTAMP(3),
ADD COLUMN "pickedUpAt" TIMESTAMP(3),
ADD COLUMN "deliveredAt" TIMESTAMP(3),
ADD COLUMN "canceledAt" TIMESTAMP(3);
